### ISSUE TITLE
Automatically explicitly list all the exports from a package?

### ISSUE THREAD

**Issue by eeue56** [avh4/elm-upgrade#34] opened 2018-05-10 17:04 UTC
In 0.18, you can export `(..)` from a module (e.g `module Lazy.List exposing (..)`), and that's fine. 

In 0.19, you must explicitly list each of them. However -- if the package existed in 0.18, the exposed things were already explicitly listed in the docs. Maybe we can pull the names from the docs and fill the `(..)` exposing gap

**Comment by avh4** [comment] 2018-05-16 03:48
The 0.19 upgrade docs don't mention that this is a change in 0.19 -- is it a change that was intended?

**Comment by eeue56** [comment] 2018-05-16 11:51
Yes, I think so.

**Comment by avh4** [comment] 2018-05-17 07:00
Fixed in 0.19.0-rc8

**Closed by avh4** 2018-05-17 07:00 UTC
Labels: elm-format, waiting-elm-format-release
